sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.5"
services:
  - mysql
install:
  - pip install -r requirements.txt
before_script:
  - mysql -e 'DROP DATABASE IF EXISTS propel; CREATE DATABASE propel' -u root
script:
  - flake8 propel