"""Add schedule_latest to Tasks

Revision ID: aa83a25570e9
Revises: a6b38808d036
Create Date: 2018-07-28 22:06:12.244479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa83a25570e9'
down_revision = 'a6b38808d036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('schedule_latest', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'schedule_latest')
    # ### end Alembic commands ###
